name: 'keihin00787'
on:
  schedule:
    - cron:  '0 15 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: commit
        id: commit
        run: |
          id="keihin00787"
          name="京王線橋梁上流"
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          year=`TZ=Asia/Tokyo date '+%Y' --date '1 day ago'`
          month=`TZ=Asia/Tokyo date '+%m' --date '1 day ago'`
          date=`TZ=Asia/Tokyo date '+%d' --date '1 day ago'`
          mkdir -p images
          number=1
          images=`curl -sS https://dapcdfpydg7sr.cloudfront.net/${id}/images/${year}/${month}/${date}/images.txt`
          for imagepath in $images
          do
            url="https://dapcdfpydg7sr.cloudfront.net/${imagepath}"
            num=`printf %03d $number`
            curl -sS $url > "images/${num}.jpg"
            number=$((number+1))
          done
          ffmpeg -r 10 -i images/%03d.jpg -vcodec libx264 -pix_fmt yuv420p -r 40 -strict -2 -acodec aac out.mp4
          message="${year}年${month}月${date}日に配信された、${name}にある多摩川ライブカメラの映像です。%0Ahttps://www.livercam.net/cameras/${id}/date/${year}${month}${date}"
          echo "::set-output name=MESSAGE::${message}"
      - name: Tweet
        id: tweet
        uses: labeneko/tweet@main
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.KEIHIN_00787_TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.KEIHIN_00787_TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            ${{ steps.commit.outputs.MESSAGE }}
          media_paths: |
            out.mp4
      - run: echo ${{ steps.tweet.outputs.response }}
