name: 'Tweet test'
on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: commit
        run: |
            curl -sS https://www.home-movie.biz/mov/hts-samp001.mp4 > sample.mp4
      - name: Tweet
        id: tweet
        uses: labeneko/tweet@main
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            test
          media_paths: |
            sample.mp4
      - run: echo ${{ steps.tweet.outputs.response }}
