name: 'Tweet test'
on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: commit
        run: |
            curl -sS $url > "images/${num}.jpg"
            number=$((number+1))
            curl -O -sS https://help.twitter.com/content/dam/help-twitter/brand/logo.png
      - name: Tweet
        id: tweet
        uses: snow-actions/tweet@v1.1.1
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            test
          media_paths: |
            logo.png
      - run: echo ${{ steps.tweet.outputs.response }}
