name: 'Tweet test'
on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: commit
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          year=`TZ=Asia/Tokyo date '+%Y' --date '1 day ago'`
          month=`TZ=Asia/Tokyo date '+%m' --date '1 day ago'`
          date=`TZ=Asia/Tokyo date '+%d' --date '1 day ago'`
          mkdir -p images
          number=1
          images=`curl -sS https://dapcdfpydg7sr.cloudfront.net/keihin00787/images/${year}/${month}/${date}/images.txt`
          for imagepath in $images
          do
            url="https://dapcdfpydg7sr.cloudfront.net/${imagepath}"
            num=`printf %03d $number`
            curl -sS $url > "images/${num}.jpg"
            number=$((number+1))
          done
          ffmpeg -r 10 -i images/%03d.jpg -vcodec libx264 -pix_fmt yuv420p -r 40 -strict -2 -acodec aac out.mp4
      - name: Tweet
        id: tweet
        uses: labeneko/tweet@main
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            "${year}年${month}月${date}日に配信された、京王線橋梁上流にある多摩川ライブカメラの映像です\nhttps://www.livercam.net/cameras/keihin00787/date/${year}${month}${date}"
          media_paths: |
            out.mp4
      - run: echo ${{ steps.tweet.outputs.response }}
